### ISSUE TITLE
Bug in running test_models.py

### ISSUE THREAD

**Issue by jhyland01** [Goobley/python-intermediate-inflammation#4]
Failure in running pytest tests/test_models.py :
[error.txt](https://github.com/Goobley/python-intermediate-inflammation/files/8787019/error.txt)

Using environment:
[requirements.txt](https://github.com/Goobley/python-intermediate-inflammation/files/8787025/requirements.txt)

**Comment by Goobley** [comment]
As highlighted by the code in `error.txt`, which is not the same as present in the repo. Compare the `patient_normalise` in your output to https://github.com/Goobley/python-intermediate-inflammation/blob/79e256ed2cd1d2ed120ae41c5bb327b6b49bcede/inflammation/models.py#L50

I expect that you have run the tests for this version of the code against a different installed version, probably your own. Please ensure you've followed the installation instructions on the readme.

If this is not the case, or you're still having issues, please reopen this.
